### ISSUE TITLE
generator identity penalty loss

### ISSUE THREAD

**Issue by zhengyuf** [marcoamonteiro/pi-GAN#6]
Hi,

Thank you very much for the well-organized repository and inspiring work! I find the codebase very clean and convenient since it has all the necessary visualization code ready.

I'm confused about one thing though: In line 278 of train.py, there is an identity penalty loss for the generator. But as far as I understand, the gradient for identity penalty does not flow through the generator because the sampling of z and pitch yaw values is not learnable. Is that right?

Cheers,
Yufeng

**Comment by ericryanchan** [comment]
Hi Yufeng,

The purpose of the identity penalty loss is to help ensure pose consistency. We approximate the pose distribution of the dataset with a Gaussian, but since the real pose distribution isn't quite Gaussian, it turns out that the model does best by letting the poses drift over time (this lets the model get more of certain poses, e.g. poses from the far edges). If we only cared about getting the best images, we would just let this happen, but experimentally it seems to degrade the 3D shapes we can extract. To help counteract this, we've included the identity loss that you noticed.

During the discriminator step, we teach the discriminator to recognize the pose, and during the generator update, we improve the generator both on the 'realness' prediction and by how closely it matched the expected pose. This improves pose consistency because it penalizes the generator for producing faces that don't conform to the canonical pose.

However, there are other ways you can maintain pose consistency! Simply training at a lower learning helps. If you have poses, training from the true pose distribution or conditioning on poses will help prevent drift as well. Let me know if this makes sense or if you have further questions!

Best,
Eric

**Comment by zhengyuf** [comment]
Hi Eric,

Thank you for your reply! It solved my confusion:)
It does make sense that identity loss would improve generated canonical pose consistency. 

Cheers,
Yufeng
